#!/usr/bin/env python3
"""Scaffold a new engagement repo for the strategic-consulting harness."""

import argparse
import re
import subprocess
import sys
from pathlib import Path

PHASE_DIRS = [
    "00-intake",
    "01-situation",
    "02-gap",
    "03-mapping",
    "04-roadmap",
    "05-handover",
    "06-retro",
]

# Minimal empty register stubs (frontmatter + header only; no entries)
_REGISTER_STUBS: dict[str, str] = {
    "_assumptions.md": """\
---
register: assumptions
harness_version: "{version}"
customer: "{customer}"
---

# Assumptions Register

<!-- Entries go here. See templates/_registers/_assumptions.md for schema. -->
""",
    "_decisions.md": """\
---
register: decisions
harness_version: "{version}"
customer: "{customer}"
---

# Decisions Register

<!-- Entries go here. See templates/_registers/_decisions.md for schema. -->
""",
    "_risks.md": """\
---
register: risks
harness_version: "{version}"
customer: "{customer}"
---

# Risk Register

<!-- Entries go here. See templates/_registers/_risks.md for schema. -->
""",
    "_contradictions.md": """\
---
register: contradictions
harness_version: "{version}"
customer: "{customer}"
---

# Contradictions Register

<!-- Entries go here. See templates/_registers/_contradictions.md for schema. -->
""",
    "_compliance.md": """\
---
register: compliance
harness_version: "{version}"
customer: "{customer}"
---

# Compliance Register

<!-- Entries go here. See templates/_registers/_compliance.md for schema. -->
""",
    "_budget.md": """\
---
register: budget
harness_version: "{version}"
customer: "{customer}"
---

# Budget Register

<!-- Entries go here. See templates/_registers/_budget.md for schema. -->
""",
}

_CLAUDE_MD_STUB = """\
# Engagement: {customer}

> Auto-generated by `harness init`. Replace every `<PLACEHOLDER>` below
> before running the first phase.

## Harness Version

harness_version: "{version}"

## Customer

customer_name: "{customer}"

## Compliance Frameworks

<!-- List all applicable frameworks, one per line. -->
<!-- Example: NIS2, ISO27001 -->
compliance_frameworks:
  - <FRAMEWORK_1>
  - <FRAMEWORK_2>

## Budget Envelope Shape

<!-- Describe the rough envelope to set expectations for roadmap items.     -->
<!-- Example: capex_y1: £50k, opex_annual: £20k, hard_limit: £200k total   -->
budget_envelope_shape: "<PLACEHOLDER: capex_y1, opex_annual, hard_limit>"

## Stakeholders

<!-- List 2–4 key contacts with roles. -->
stakeholders:
  - name: "<PLACEHOLDER>"
    role: "<PLACEHOLDER>"
  - name: "<PLACEHOLDER>"
    role: "<PLACEHOLDER>"

## Notes

<!-- Any additional context relevant to this engagement. -->
"""


def _read_harness_version() -> str:
    """Extract the first version number from the harness CHANGELOG.md."""
    changelog = Path(__file__).parent.parent / "CHANGELOG.md"
    if not changelog.exists():
        return "unknown"
    text = changelog.read_text(encoding="utf-8")
    match = re.search(r"##\s+\[(\d+\.\d+\.\d+)\]", text)
    return match.group(1) if match else "unknown"


def _scaffold(customer: str, target: Path, version: str) -> None:
    target.mkdir(parents=True, exist_ok=False)

    # Phase directories
    for phase in PHASE_DIRS:
        (target / phase).mkdir()

    # Root registers
    for filename, stub in _REGISTER_STUBS.items():
        (target / filename).write_text(
            stub.format(version=version, customer=customer),
            encoding="utf-8",
        )

    # Engagement CLAUDE.md
    (target / "CLAUDE.md").write_text(
        _CLAUDE_MD_STUB.format(version=version, customer=customer),
        encoding="utf-8",
    )


def _git_init_and_commit(target: Path, customer: str) -> None:
    env_extras: dict[str, str] = {}
    subprocess.run(["git", "init"], cwd=target, check=True, capture_output=True)
    subprocess.run(["git", "add", "."], cwd=target, check=True, capture_output=True)
    subprocess.run(
        ["git", "commit", "-m", f"chore: scaffold engagement for {customer}"],
        cwd=target,
        check=True,
        capture_output=True,
        env={**__import__("os").environ, **env_extras},
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Scaffold a new engagement repo.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("customer_name", help="Customer / engagement name (slug-safe)")
    parser.add_argument(
        "--target-dir",
        default=None,
        help="Directory to create the engagement repo in (default: ./<customer-name>)",
    )
    args = parser.parse_args(argv)

    customer: str = args.customer_name
    target = Path(args.target_dir) if args.target_dir else Path(customer)

    if target.exists() and any(target.iterdir()):
        print(
            f"error: target directory '{target}' already exists and is not empty.",
            file=sys.stderr,
        )
        return 1

    version = _read_harness_version()

    try:
        _scaffold(customer, target, version)
    except FileExistsError:
        print(
            f"error: target directory '{target}' already exists and is not empty.",
            file=sys.stderr,
        )
        return 1

    try:
        _git_init_and_commit(target, customer)
    except subprocess.CalledProcessError as exc:
        print(f"error: git init/commit failed: {exc}", file=sys.stderr)
        return 1

    print(f"Engagement repo created at: {target.resolve()}")
    print(f"  harness_version: {version}")
    print("  Edit CLAUDE.md to fill in compliance frameworks, budget, and stakeholders.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
